Repository Team-HANOI/AI-interviewer, pull requests merged in 2021-09, with the labels that each got.

#77 Fix/change config
  app/build.gradle
  app/src/main/java/com/alpaca/app/AppConfig.java
  app/src/main/java/com/alpaca/app/sample/controller/SampleController.java
  app/src/main/java/com/alpaca/app/sample/service/MemberService.java
  app/src/main/resources/application.properties
  app/src/main/resources/templates/css/main.css
  app/src/main/resources/templates/fragments/footer.html
  app/src/main/resources/templates/fragments/header.html
  app/src/main/resources/templates/fragments/main/main_header.html
  app/src/main/resources/templates/index.html
  app/src/main/resources/templates/layouts/template.html
  app/src/main/resources/templates/main.html
  app/src/main/resources/templates/main_title.html
  app/src/main/resources/templates/sample/admin.html
  app/src/main/resources/templates/sample/all.html
  app/src/main/resources/templates/sample/css/main.css
  app/src/main/resources/templates/sample/fragments/footer.html
  app/src/main/resources/templates/sample/fragments/header.html
  app/src/main/resources/templates/sample/image/austria.jpg
  app/src/main/resources/templates/sample/image/green.jpg
  app/src/main/resources/templates/sample/image/sky.jpg
  app/src/main/resources/templates/sample/image/sky2.jpg
  app/src/main/resources/templates/sample/main.html
  app/src/main/resources/templates/sample/member.html
  app/src/main/webapp/WEB-INF/views/home.jsp
  app/src/main/webapp/WEB-INF/views/include/include.jsp
  app/src/main/webapp/WEB-INF/views/index.jsp
  app/src/main/webapp/WEB-INF/views/layout/footer.jsp
  app/src/main/webapp/WEB-INF/views/layout/header.jsp
  app/src/main/webapp/WEB-INF/views/layout/top.jsp
  app/src/main/webapp/WEB-INF/views/test.jsp
Labels: :bug:bug

#80 chore: 프로젝트 기본 설정
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chore_template.md
  .github/ISSUE_TEMPLATE/docs_template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor_template.md
  Team_Project/src/main/java/com/team/interview/dao/MemberDAO.java
  Team_Project/src/main/java/com/team/interview/service/MemberService.java
  Team_Project/src/main/java/com/team/interview/vo/MemberVO.java
  Team_Project/src/main/resources/application.properties
  Team_Project/src/main/resources/mybatis-config.xml
Labels: :art:chore

#82 fix: mybatis 설정 오류 수정
  Team_Project/build.gradle
  Team_Project/src/main/resources/application.properties
  Team_Project/src/main/resources/mybatis-config.xml
  Team_Project/src/main/webapp/mybatis-config.xml
Labels: :bug:bug

#85 chore: 지영 프로젝트 통합 vo xml dao service
  Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/java/com/team/interview/vo/FileVO.java
  Team_Project/src/main/java/com/team/interview/vo/PageInfo.java
  Team_Project/src/main/java/com/team/interview/vo/RCommVO.java
  Team_Project/src/main/java/com/team/interview/vo/ReviewVO.java
  Team_Project/src/main/resources/mybatis/mappers/review.xml
Labels: :art:chore

#88 chore: 스프링 시큐리티 초기 설정
  Team_Project/build.gradle
  Team_Project/src/main/java/com/team/interview/config/SecurityConfig.java
  Team_Project/src/main/java/com/team/interview/controller/SampleController.java
  Team_Project/src/main/java/com/team/interview/dao/MemberDAO.java
  Team_Project/src/main/java/com/team/interview/security/dto/AuthMemberDTO.java
  Team_Project/src/main/java/com/team/interview/security/handler/CustomLoginSuccessHandler.java
  Team_Project/src/main/java/com/team/interview/security/service/CustomOAuth2UserDetailsService.java
  Team_Project/src/main/java/com/team/interview/security/service/CustomUserDetailsService.java
  Team_Project/src/main/java/com/team/interview/vo/AuthVO.java
  Team_Project/src/main/java/com/team/interview/vo/MemberVO.java
  Team_Project/src/main/resources/application-oauth.properties
  Team_Project/src/main/resources/application.properties
  Team_Project/src/main/resources/log4jdbc.log4j2.properties
  Team_Project/src/main/resources/mybatis-config.xml
  Team_Project/src/main/resources/mybatis/mappers/Member.xml
  Team_Project/src/main/webapp/WEB-INF/views/sample/admin.jsp
  Team_Project/src/main/webapp/WEB-INF/views/sample/all.jsp
  Team_Project/src/main/webapp/WEB-INF/views/sample/member.jsp
  Team_Project/src/test/java/com/team/interview/test/MemberTests.java
Labels: :art:chore

#106 feat: 커스텀 로그인 기능 구현
  Team_Project/src/main/java/com/team/interview/config/CustomAuthenticationFailureHandler.java
  Team_Project/src/main/java/com/team/interview/config/SecurityConfig.java
  Team_Project/src/main/java/com/team/interview/controller/LoginController.java
  Team_Project/src/main/java/com/team/interview/controller/SampleController.java
  Team_Project/src/main/java/com/team/interview/security/dto/AuthMemberDTO.java
  Team_Project/src/main/java/com/team/interview/security/handler/CustomLoginSuccessHandler.java
  Team_Project/src/main/java/com/team/interview/security/service/CustomOAuth2UserDetailsService.java
  Team_Project/src/main/java/com/team/interview/security/service/CustomUserDetailsService.java
  Team_Project/src/main/java/com/team/interview/service/MemberService.java
  Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java
  Team_Project/src/main/java/com/team/interview/vo/CompanyVO.java
  Team_Project/src/main/java/com/team/interview/vo/MemberVO.java
  Team_Project/src/main/resources/application-oauth.properties
  Team_Project/src/main/resources/mybatis/mappers/member.xml
  Team_Project/src/main/webapp/WEB-INF/views/security/customLogin.jsp
  Team_Project/src/test/java/com/team/interview/test/MemberTests.java
Labels: :sparkles:feature

#113 board_review 프로젝트 통합 ver2
  Team_Project/build.gradle
  Team_Project/src/main/java/com/team/interview/controller/ReviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/application.properties
  Team_Project/src/main/resources/mybatis-config.xml
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/resources/static/js/board_review.js
  Team_Project/src/main/resources/static/style/board_review.css
  Team_Project/src/main/webapp/WEB-INF/views/board/err.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/write.jsp
Labels: :zap:refactor

#118 test: tbl_company에 더미데이터 삽입
  Team_Project/src/main/java/com/team/interview/dao/CompanyDAO.java
  Team_Project/src/main/java/com/team/interview/dao/MemberDAO.java
  Team_Project/src/main/java/com/team/interview/security/dto/AuthMemberDTO.java
  Team_Project/src/main/java/com/team/interview/security/service/CustomOAuth2UserDetailsService.java
  Team_Project/src/main/java/com/team/interview/security/service/CustomUserDetailsService.java
  Team_Project/src/main/java/com/team/interview/vo/CompanyVO.java
  Team_Project/src/main/java/com/team/interview/vo/MemberVO.java
  Team_Project/src/main/resources/mybatis-config.xml
  Team_Project/src/main/resources/mybatis/mappers/company.xml
  Team_Project/src/main/webapp/WEB-INF/views/security/customLogin.jsp
  Team_Project/src/test/java/com/team/interview/test/MemberTests.java
Labels: 🧪test

#131 Feat/jy
  Team_Project/build.gradle
  Team_Project/src/main/java/com/team/interview/controller/ReviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/application.properties
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/resources/static/js/board_detail.js
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Labels: :sparkles:feature

#143 review 게시판 수정버튼 완료 / 네비게이션 활성화
  Team_Project/src/main/java/com/team/interview/controller/ReviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/webapp/WEB-INF/views/board/board_common/board_nav.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/modify.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp
Labels: :sparkles:feature

#147 feat: 기업회원 회원가입 기능을 구현
  Team_Project/build.gradle
  Team_Project/src/main/java/com/team/interview/controller/LoginController.java
  Team_Project/src/main/java/com/team/interview/controller/MemberController.java
  Team_Project/src/main/java/com/team/interview/controller/MyPageController.java
  Team_Project/src/main/java/com/team/interview/controller/SampleController.java
  Team_Project/src/main/java/com/team/interview/dao/CompanyDAO.java
  Team_Project/src/main/java/com/team/interview/dao/MemberDAO.java
  Team_Project/src/main/java/com/team/interview/dao/ProfileDAO.java
  Team_Project/src/main/java/com/team/interview/security/dto/AuthMemberDTO.java
  Team_Project/src/main/java/com/team/interview/security/service/CommonOAuth2UserDetailsService.java
  Team_Project/src/main/java/com/team/interview/security/service/CommonUserDetailsService.java
  Team_Project/src/main/java/com/team/interview/security/service/CompanyUserDetailsServiceImpl.java
  Team_Project/src/main/java/com/team/interview/service/MemberService.java
  Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java
  Team_Project/src/main/java/com/team/interview/vo/MemberVO.java
  Team_Project/src/main/resources/mybatis-config.xml
  Team_Project/src/main/resources/mybatis/mappers/company.xml
  Team_Project/src/main/resources/mybatis/mappers/member.xml
  Team_Project/src/main/resources/mybatis/mappers/profile.xml
  Team_Project/src/main/resources/static/image/alpaca.jpg
  Team_Project/src/main/resources/static/image/upload.jpg
  Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp
  Team_Project/src/main/webapp/WEB-INF/views/common/header.jsp
  Team_Project/src/main/webapp/WEB-INF/views/member/join_com.jsp
  Team_Project/src/main/webapp/WEB-INF/views/member/join_indv.jsp
  Team_Project/src/main/webapp/WEB-INF/views/member/join_indv_extra.jsp
  Team_Project/src/main/webapp/WEB-INF/views/member/join_indv_tech.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/profile.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/profile_edit.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/pwchange.jsp
  Team_Project/src/main/webapp/WEB-INF/views/sample/ex1.jsp
  Team_Project/src/main/webapp/WEB-INF/views/security/userLogin.jsp
Labels: :sparkles:feature

#156 board_review 게시판 로그인 세션연동 테스트
  Team_Project/build.gradle
  Team_Project/src/main/java/com/team/interview/controller/InterviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/application.properties
  Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/write.jsp
Labels: 🧪test

#159 board_review 면접후기게시판 로그인 연동 완료
  Team_Project/src/main/java/com/team/interview/config/SecurityConfig.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java
  Team_Project/src/main/resources/static/js/board_detail.js
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/write.jsp
Labels: :sparkles:feature

#166 feat: 프로필 관리 페이지 추가
  Team_Project/src/main/java/com/team/interview/controller/MemberController.java
  Team_Project/src/main/java/com/team/interview/controller/MyPageController.java
  Team_Project/src/main/java/com/team/interview/dao/MemberDAO.java
  Team_Project/src/main/java/com/team/interview/dao/ProfileDAO.java
  Team_Project/src/main/java/com/team/interview/security/service/CommonOAuth2UserDetailsService.java
  Team_Project/src/main/java/com/team/interview/service/MemberService.java
  Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java
  Team_Project/src/main/java/com/team/interview/service/ProfileService.java
  Team_Project/src/main/java/com/team/interview/service/ProfileServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/member.xml
  Team_Project/src/main/resources/mybatis/mappers/profile.xml
  Team_Project/src/main/resources/static/image/alpaca.jpg
  Team_Project/src/main/resources/static/image/default_pf_img.jpg
  Team_Project/src/main/webapp/WEB-INF/views/mypage/profile.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/profile_edit.jsp
Labels: :sparkles:feature

#169 feat:
  Team_Project/src/main/java/com/team/interview/controller/MemberController.java
  Team_Project/src/main/java/com/team/interview/controller/MyPageController.java
  Team_Project/src/main/java/com/team/interview/dao/InterviewRecordDAO.java
  Team_Project/src/main/java/com/team/interview/service/InterviewRecordService.java
  Team_Project/src/main/java/com/team/interview/service/InterviewRecordServiceImpl.java
  Team_Project/src/main/java/com/team/interview/service/MemberServiceImpl.java
  Team_Project/src/main/java/com/team/interview/vo/AnswerVO.java
  Team_Project/src/main/java/com/team/interview/vo/Criteria.java
  Team_Project/src/main/java/com/team/interview/vo/InterviewRecordVO.java
  Team_Project/src/main/java/com/team/interview/vo/PageDTO.java
  Team_Project/src/main/java/com/team/interview/vo/QuestionVO.java
  Team_Project/src/main/resources/mybatis-config.xml
  Team_Project/src/main/resources/mybatis/mappers/interviewRecord.xml
  Team_Project/src/main/webapp/WEB-INF/views/member/join_com.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview_detail.jsp
  Team_Project/src/test/java/com/team/interview/test/MemberTests.java
Labels: :sparkles:feature

#176 feat: 내면접 페이지에서 질문, 답변 음성 듣기 기능 추가
  Team_Project/src/main/java/com/team/interview/controller/MyPageController.java
  Team_Project/src/main/java/com/team/interview/dao/InterviewRecordDAO.java
  Team_Project/src/main/java/com/team/interview/service/InterviewRecordService.java
  Team_Project/src/main/java/com/team/interview/service/InterviewRecordServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/interviewRecord.xml
  Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview_detail.jsp
Labels: :sparkles:feature

#174 보드 댓글기능 작성자 프로필 사진 코드 완성
  Team_Project/src/main/java/com/team/interview/controller/ReviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Labels: :sparkles:feature

#178 chore: 잔디 템플릿 추가
  Team_Project/src/main/java/com/team/interview/controller/InterviewController.java
  Team_Project/src/main/java/com/team/interview/controller/MainController.java
  Team_Project/src/main/java/com/team/interview/controller/MyPageController.java
  Team_Project/src/main/java/com/team/interview/controller/SampleController.java
  Team_Project/src/main/resources/static/zandi.css
  Team_Project/src/main/resources/static/zandi.js
  Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview.jsp
  Team_Project/src/main/webapp/WEB-INF/views/mypage/myinterview_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/script.js
  Team_Project/src/main/webapp/WEB-INF/views/style.css
  Team_Project/src/main/webapp/WEB-INF/views/zandi.jsp
Labels: :art:chore

#187 feat: 멘토링 지원자 리스트 페이지 추가
  Team_Project/src/main/java/com/team/interview/controller/MyPageController.java
  Team_Project/src/main/java/com/team/interview/vo/MentormodeVO.java
  Team_Project/src/main/resources/mybatis/mappers/mentormode.xml
  Team_Project/src/main/webapp/WEB-INF/views/mypage/mentoring_com.jsp
Labels: :sparkles:feature

#188 feat: 게시판 본글 댓글 삭제기능 코드완료
  Team_Project/src/main/java/com/team/interview/controller/ReviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Labels: :sparkles:feature

#189 refactor: 통합서버 application properties 경로 수정
  Team_Project/src/main/resources/application.properties
Labels: :zap:refactor

#204 refactor: 게시판 이전글 다음글 에러코드 수정 및 프론트 디테일 수정
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/resources/static/style/board_comment.css
  Team_Project/src/main/resources/static/style/board_detail2.css
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Labels: :zap:refactor

#206 refactor: 보드삭제 기능 에러 코드 수정
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/dao/ReviewDAO.java
  Team_Project/src/main/java/com/team/interview/service/ReviewService.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
  Team_Project/src/main/resources/mybatis/mappers/review.xml
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/board_detail2.css
Labels: :zap:refactor

#211 feat: 답글달기 버튼 클릭시 박스나타나기 기능 코드 완료 (광진님 최고)
  Team_Project/src/main/resources/static/js/board_detail.js
  Team_Project/src/main/resources/static/style/board_comment.css
  Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review2.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/interview/recruit.jsp
Labels: :zap:refactor

#217 chore : 보드 프론트 정리
  Team_Project/src/main/resources/static/js/board_detail.js
  Team_Project/src/main/resources/static/style/board_comment.css
  Team_Project/src/main/resources/static/style/board_detail2.css
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Labels: :art:chore

#222 feat: 매일 자정마다 잔디 빈칸을 하나씩 생성
  Team_Project/build.gradle
  Team_Project/src/main/java/com/team/interview/TeamProjectApplication.java
  Team_Project/src/main/java/com/team/interview/batch/jobs/JandiConfig.java
  Team_Project/src/main/java/com/team/interview/batch/schedulers/JandiScheduler.java
  Team_Project/src/main/java/com/team/interview/batch/tasklets/JandiTasklet.java
  Team_Project/src/main/resources/application.properties
Labels: :sparkles:feature

#226 refactor : 면접후기 게시판 글쓰기 수정하기 프론트 수정완료
  Team_Project/src/main/resources/static/style/board_write.css
  Team_Project/src/main/webapp/WEB-INF/views/board/modify.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/write.jsp
Labels: :zap:refactor

#227 refactor: ssl key 수정완료
  Team_Project/src/main/resources/alpaca.p12
  Team_Project/src/main/resources/application.properties
Labels: :zap:refactor

#242 fix : 대댓글 기능 통합버전 이메일 오류 코드 수정
  Team_Project/src/main/java/com/team/interview/controller/ReviewController.java
  Team_Project/src/main/java/com/team/interview/controller/ReviewControllerImpl.java
  Team_Project/src/main/java/com/team/interview/service/ReviewServiceImpl.java
Labels: :art:chore

#254 refactor: 면접후기게시판 프로필사진 에러코드 수정
  Team_Project/src/main/resources/static/style/board_comment.css
  Team_Project/src/main/resources/static/style/board_detail.css
  Team_Project/src/main/resources/static/style/board_detail2.css
  Team_Project/src/main/webapp/WEB-INF/views/board/review.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review2.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail2.jsp
Labels: :zap:refactor

#256 feat: 대댓글 수정삭제 권한부여
  Team_Project/src/main/resources/static/js/board_detail.js
  Team_Project/src/main/webapp/WEB-INF/views/board/review_detail.jsp
Labels: :sparkles:feature
