Repository Team-HANOI/AI-interviewer, pull requests merged in 2021-08, with the labels that each got.

#32 docs : Update stacks.txt 기술스택 데이터 정제
  resources/document/stack정리한거.txt
  stack정리한거.txt
Labels: :memo:documentation

#35 chore : Add MemberRole.java 회원권한 enum 적용
  app/src/main/java/com/alpaca/app/sample/domain/AuthVO.java
  app/src/main/java/com/alpaca/app/sample/domain/MemberRole.java
  app/src/main/java/com/alpaca/app/sample/domain/MemberVO.java
  app/src/main/java/com/alpaca/app/security/service/CustomOAuth2UserDetailsService.java
  app/src/main/java/com/alpaca/app/security/service/CustomUserDetailsService.java
  app/src/main/resources/mybatis-mapper/MemberMapper.xml
  app/src/test/java/com/alpaca/app/security/MemberTests.java
Labels: :art:chore

#37 [Feature/login] LoginSuccessHandler & loh4j2 설정
  app/build.gradle
  app/logs/logback.log
  app/src/main/java/com/alpaca/app/config/SecurityConfig.java
  app/src/main/java/com/alpaca/app/sample/domain/MemberVO.java
  app/src/main/java/com/alpaca/app/security/handler/LoginSuccessHandler.java
  app/src/main/java/com/alpaca/app/security/service/CustomOAuth2UserDetailsService.java
  app/src/main/java/com/alpaca/app/security/service/CustomUserDetailsService.java
  app/src/main/resources/application.properties
  app/src/main/resources/log4jdbc.log4j2.properties
  app/src/main/resources/logback-spring.xml
  app/src/main/resources/mybatis-mapper/MemberMapper.xml
  app/src/test/java/com/alpaca/app/security/MemberTests.java
Labels: :sparkles:feature, :art:chore

#41 feat : hr.stack 테이블 업로드
  resources/DML/JOB_POSTING_202108141316.sql
  resources/DML/STACK_202108141248.sql
Labels: :memo:documentation, :sparkles:feature

#44 feat : Springbatch_prototype
  resources/jobposting_batch_ptorotype/bin/test/Array_Test.class
  resources/jobposting_batch_ptorotype/bin/test/Base.class
  resources/jobposting_batch_ptorotype/bin/test/Base_Final.class
  resources/jobposting_batch_ptorotype/bin/test/BoardInfo_noTouch_Final.class
  resources/jobposting_batch_ptorotype/bin/test/Board_info_StackArray_noTouch_SizeTest.class
  resources/jobposting_batch_ptorotype/bin/test/Board_info_stackArray_HashSet_ArrayTest.class
  resources/jobposting_batch_ptorotype/bin/test/Stack_Num_noTouch_Final.class
  resources/jobposting_batch_ptorotype/bin/test/Tag_stack_noTouch.class
  resources/jobposting_batch_ptorotype/bin/test/Title_noTouch_Dummy.class
  resources/jobposting_batch_ptorotype/jsoup-1.13.1.jar
  resources/jobposting_batch_ptorotype/ojdbc6.jar
  resources/jobposting_batch_ptorotype/src/test/Array_Test.java
  resources/jobposting_batch_ptorotype/src/test/Base.java
  resources/jobposting_batch_ptorotype/src/test/Base_Final.java
  resources/jobposting_batch_ptorotype/src/test/BoardInfo_noTouch_Final.java
  resources/jobposting_batch_ptorotype/src/test/Board_info_StackArray_noTouch_SizeTest.java
  resources/jobposting_batch_ptorotype/src/test/Board_info_stackArray_HashSet_ArrayTest.java
  resources/jobposting_batch_ptorotype/src/test/Stack_Num_noTouch_Final.java
  resources/jobposting_batch_ptorotype/src/test/Tag_stack_noTouch.java
  resources/jobposting_batch_ptorotype/src/test/Title_noTouch_Dummy.java
  resources/jobposting_batch_ptorotype/설명서.txt
Labels: :memo:documentation, :sparkles:feature

#50 docs : ssml의 스펙과 사용시 기대되는 효과
  resources/document/ssml스펙체크/EX1.mp3
  resources/document/ssml스펙체크/EX1.ssml.mp3
  resources/document/ssml스펙체크/EX2.mp3
  resources/document/ssml스펙체크/EX2.ssml.mp3
  resources/document/ssml스펙체크/EX3.mp3
  resources/document/ssml스펙체크/EX3.ssml.mp3
  resources/document/ssml스펙체크/EX4.mp3
  resources/document/ssml스펙체크/EX4.ssml.mp3
  resources/document/ssml스펙체크/EX5.mp3
  resources/document/ssml스펙체크/EX5.ssml.mp3
  resources/document/ssml스펙체크/SSML 스펙체크.md
Labels: :memo:documentation
